Add timer after cast functionality
Brusalk/EventHorizon_Continued pull request #129
Opened 2022-09-18 21:10 UTC by StragaSevera

Added functionality for creating timers after a spell had been cast. This is useful for situations like Paladin Consecration or Mage Rune of Power, when your ability creates some object that is not trackable via common buffs or debuffs.
The syntax is:
```lua
  self:newSpell({
    -- ...
    timerAfterCast = {26573, 12}, -- spellID and the length of timer
  })
```

2022-09-18 21:48 UTC, Brusalk requested changes
Thanks for the PR @StragaSevera! Just a couple questions

2022-09-18 21:48 UTC, Brusalk commented on EventHorizon/EventHorizon.lua
> +    timerAfterCast = self.timerAfterCast
This looks like a leaked global. Can you add the local qualifier here?

2022-09-18 21:48 UTC, Brusalk commented on EventHorizon/EventHorizon.lua
> +  local self,time, event, hideCaster, srcguid,srcname,srcflags,srcraidflags,destguid,destname,destflags, destraidflags,spellid,spellname = ...
When were these added? Have things just been broken for a while? Do they need to be added to the spellframe CLEU handler as well?

2022-09-18 21:52 UTC, StragaSevera commented on EventHorizon/EventHorizon.lua
> +  local self,time, event, hideCaster, srcguid,srcname,srcflags,srcraidflags,destguid,destname,destflags, destraidflags,spellid,spellname = ...
Yes, they were added, and this functionality was broken. I don't think this is nessesary, spellframe doesn't need this args =-)

2022-09-18 21:52 UTC, StragaSevera commented on EventHorizon/EventHorizon.lua
> +    timerAfterCast = self.timerAfterCast
My bad, will fix it =-)

2022-09-18 22:51 UTC, Brusalk commented on EventHorizon/EventHorizon.lua
> +  local self,time, event, hideCaster, srcguid,srcname,srcflags,srcraidflags,destguid,destname,destflags, destraidflags,spellid,spellname = ...
Problem is they're positional args so what used to be interpreted by downstream code as `destguid` was actually receiving the value of srcraidflags (and more offset downstream) since whenever they made the change. I guess it didn't actually break anything for anyone? I'm kinda surprised by that since spellID/spellName are pretty integral to the addon's behavior

2022-09-19 07:02 UTC, StragaSevera commented on EventHorizon/EventHorizon.lua
> +  local self,time, event, hideCaster, srcguid,srcname,srcflags,srcraidflags,destguid,destname,destflags, destraidflags,spellid,spellname = ...
Yes, that's strange, but from my understanding, the CLEU functionality is used only in the DoT module, so it was not noticeable.

2022-09-21 03:03 UTC, Cluuey commented on EventHorizon/EventHorizon.lua
> +  local self,time, event, hideCaster, srcguid,srcname,srcflags,srcraidflags,destguid,destname,destflags, destraidflags,spellid,spellname = ...
> 

I vaguely recall someone requesting to track something via spell id instead of name.
I've not played the game for a few months now, I didn't leave the Discord server though as I think I've still been helpful.

2022-09-21 10:13 UTC, StragaSevera commented on EventHorizon/EventHorizon.lua
> +  local self,time, event, hideCaster, srcguid,srcname,srcflags,srcraidflags,destguid,destname,destflags, destraidflags,spellid,spellname = ...
Yes, it was me who asked for this. Maybe I'll do it, but not now =-)

2022-09-21 10:13 UTC, StragaSevera commented on EventHorizon/EventHorizon.lua
> +    timerAfterCast = self.timerAfterCast
Fixed.

2023-01-02 20:18 UTC, Brusalk approved these changes

2023-01-02 20:19 UTC, merged